version: "2"
services:
  app:
    build: ./Audiophile
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: arm64v8/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
