version: "2"
services:
  app:
    build: ./Audiophile
    links:
      - dbcont
    ports:
      - "5000:5000"
    depends_on:
        dbcont:
            condition: service_healthy
  dbcont:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
