version: "2"
services:
  app:
    build: .
    links:
      - dbcont
    ports:
      - "5000:5000"
    depends_on:
        dbcont:
            condition: service_healthy
  dbcont:
    image: mariadb
    expose:
     - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: audiophile
      MYSQL_USER: audiophile
      MYSQL_PASSWORD: password
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
volumes:
  dbdata: